### ISSUE TITLE
os.setupTun is not a function

### ISSUE THREAD

**Issue by zoeyronain** [bemehiser/Tether#4]
OS: Ubuntu Linux 18.10 x64

I'm unable to get the tether to start on Linux, and it's giving me:

Opening tun device.
Opening tun device: /dev/net/tun
Opening tun device: null
unable to open tun/tap device.
TypeError: os.setupTun is not a function
    at new tun (/home/zoey/Desktop/Tether/node-tuntap/tuntap.js:111:6)
    at createTun (/home/zoey/Desktop/Tether/node-tuntap/tether.js:42:15)
    at Object.<anonymous> (/home/zoey/Desktop/Tether/node-tuntap/tether.js:242:1)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)

I couldn't get the node version included compiled but I already have node v11.3.0 installed on my machine. I changed the node variables to point to that instead of the node folder in the archive.

**Comment by kevinaj** [comment]
[SetupTun is a method](https://github.com/bemehiser/Tether/blob/master/node/src/node_os.cc#L255) added to the stock node_os.cc in the included source. This is why you have to compile this particular version of NodeJS for tether to work.
