### ISSUE TITLE
Error Executing run.sh

### ISSUE THREAD

**Issue by Dysfeathered** [bemehiser/Tether#5]
I had an issue executing run.sh. the following output was displayed:

```
~/Downloads/Tether-master
Starting Tether...
adb server version (40) doesn't match this client (36); killing...
* daemon started successfully *
Opening tun device.
Opening tun device: /dev/net/tun
Forking worker.
Tun/tap device IP: 10.0.0.1
Reading tun/tap device... 
Opening tun device.
adb binary path: "/home/ubreakifix/Downloads/Tether-master/linux/adb"
Checking phone status...
tun worker initialized.
Fatal error setting up TCP listener. (Exiting)
A possible cause may be that a "node.exe" processes was left dangling.
Please kill any node processes you find running.
This may also be cause by a firewall that disallows connections to Tether.

/home/ubreakifix/Downloads/Tether-master/node-tuntap/tuntap.js:558
      exitTether();
      ^
ReferenceError: exitTether is not defined
    at Server.<anonymous> (/home/ubreakifix/Downloads/Tether-master/node-tuntap/tuntap.js:558:7)
    at Server.EventEmitter.emit (events.js:96:17)
    at Server._listen2.self._handle.onconnection (net.js:894:14)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
TCP Catcher worker has died. Exiting.
{ '0': 1, '1': null }
```

I am compiling this under Ubuntu Bionic installed to a Macbook Pro A1278 with a Core i5 processor, so amd64 architecture. I followed the following method to compile and install the dependencies every command was run through sudo.

```
apt-get install -y libssl-dev cmake build-essential g++ libncurses5 python npm
npm install chainsaw
cd ./node
./configure --without-snapshot
CXXFLAGS=-fpermissive
cd ..
./linux/run.sh
```
I also followed CrossfireSoftwarez Solution in the following link:
[https://github.com/bemehiser/Tether/issues/1](https://github.com/bemehiser/Tether/issues/1)

Also, I had originally tried to compile nodejs-legacy from the included ./node directory. However the process outputted as such.

 ```
 LINK(target) /home/ubreakifix/Downloads/Tether-master/node/out/Release/node: Finished
  touch /home/ubreakifix/Downloads/Tether-master/node/out/Release/obj.target/node_dtrace_header.stamp
  touch /home/ubreakifix/Downloads/Tether-master/node/out/Release/obj.target/node_dtrace_provider.stamp
  touch /home/ubreakifix/Downloads/Tether-master/node/out/Release/obj.target/node_dtrace_ustack.stamp
  touch /home/ubreakifix/Downloads/Tether-master/node/out/Release/obj.target/node_etw.stamp
make[1]: Leaving directory '/home/ubreakifix/Downloads/Tether-master/node/out'
ln -fs out/Release/node node
```
I'm not entirely sure what I've done wrong. I know this program is in need of some serious maintenance and it's essentially up to us, the community, to patch and bring it into modern times. but I could use a little help here. I've been trying for a day to get this program to run properly. and I'm running out of ideas.

Thanks!

**Comment by Dysfeathered** [comment]
I corrected the adb error. But the tcp listener fatality still remains.

**Comment by Dysfeathered** [comment]
Firewall is not enabled. I checked with ufw. I also killed any node processes with pkill -ef node

**Comment by alecGraves** [comment]
Im on Debian 9, and I had the exact same issue. I fixed the issue with ```sudo apt-get install net-tools```, which installs required ```ifconfig``` and ```route``` command-line tools.

The error was because the server was listening to an ip address (10.0.0.1) that was never created. On linux, the code executes [some scripts to manage interfaces](https://github.com/bemehiser/Tether/tree/master/node-tuntap/linux). For me, the scripts were failing due to not having ```ifconfig``` installed. One option would be to detect this and use the new ```ip``` command when ```ifconfig``` is not there, but on debian (or ubuntu) you can install ```ifconfig``` pretty easily for now.

**Comment by Dysfeathered** [comment]
ifconfig should be standard to ubuntu but route maybe what I was missing. Thanks for the suggestion. I'll dredge up the source and try again. I'll post what happens.

**Comment by brad** [comment]
@Dysfeathered Any luck on this? I'm running into this now.

**Comment by brad** [comment]
In my case, the issue turned out to be that I had a system nodejs installed that conflicted with the one shipped with this package. I removed that and the problem went away

**Comment by carlcrott** [comment]
Im hitting this same error:

```
sudo linux/run.sh
~/Tether
Starting Tether...
Opening tun device.
Opening tun device: /dev/net/tun
Forking worker.
Tun/tap device IP: 10.0.0.1
Reading tun/tap device... 
Opening tun device.
adb binary path: "/home/winsux/Tether/linux/adb"
Checking phone status...
tun worker initialized.
Fatal error setting up TCP listener. (Exiting)
A possible cause may be that a "node.exe" processes was left dangling.
Please kill any node processes you find running.
This may also be cause by a firewall that disallows connections to Tether.

/home/winsux/Tether/node-tuntap/tuntap.js:558
      exitTether();
      ^
ReferenceError: exitTether is not defined
    at Server.<anonymous> (/home/winsux/Tether/node-tuntap/tuntap.js:558:7)
    at Server.EventEmitter.emit (events.js:96:17)
    at Server._listen2.self._handle.onconnection (net.js:894:14)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
TCP Catcher worker has died. Exiting.
{ '0': 1, '1': null }

```

But after running a combination of the bug-fixes mentioned above:

> In my case, the issue turned out to be that I had a system nodejs installed that conflicted with the one shipped with this package. I removed that and the problem went away

Which I had because I used the chainsaw workaround mentioned here:

https://github.com/bemehiser/Tether/issues/1

However removing the default npm installation did not fix the above error.


Installing the tools mentioned by AlecGraves got me further:
`sudo apt-get install net-tools`

where I now get a repeating error like this:
```

Checking phone status...
R********H Connecting to device.
R********H Checking if package is installed.
Error listing pacakges. Assuming Tether.apk is already installed.
R********H Setting up adb port forwarding to port 30002.
R********H adb port forwarding results:
{ '0': 
   { [Error: Command failed: error: device unauthorized.
   This adb server's $ADB_VENDOR_KEYS is not set
   Try 'adb kill-server' if that seems wrong.
   Otherwise check for a confirmation dialog on your device.
   ] killed: false, code: 1, signal: null },
  '1': '',
  '2': 'error: device unauthorized.\nThis adb server\'s $ADB_VENDOR_KEYS is not set\nTry \'adb kill-server\' if that seems wrong.\nOtherwise check for a confirmation dialog on your device.\n' }
R********H Error forwarding: 
{ [Error: Command failed: error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
] killed: false, code: 1, signal: null }
R********H Creating relay for device.
R********H Tether error:
{ '0': 
   { [Error: connect ECONNREFUSED]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect' } }
cleaing up relay connection
R********H Tether connection closed.
cleaing up relay connection
R********H Tether connection closed.
R********H Creating relay for device.
R********H Tether error:
{ '0': 
   { [Error: connect ECONNREFUSED]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect' } }
cleaing up relay connection
R********H Tether connection closed.
cleaing up relay connection
R********H Tether connection closed.


```

So I think the final fix for me is configuring ADB:

This adb server's $ADB_VENDOR_KEYS is not set


After configuring adb for my operating system everything SEEMS to be working save for the fact the connection speed seems hit-or-miss.

Googles speed test will average something like 2mbps but then spike to 50mbps, yet videos download slowly, so I think the traffic is still being throttled.

Is there anyway to de-restrict the bandwidth by hiding what the tethering is being used for?

**Comment by JuPlutonic** [comment]
@carlcrott https://stackoverflow.com/questions/23081263/adb-android-device-unauthorized
