### ISSUE TITLE
support for 64 bits

### ISSUE THREAD

**Issue by emiliocamposmartin** [bemehiser/Tether#7]
Is 64 bit supported? I am trying to run this app in 64 bit and it seems like adb links against libncurses.so.5 but when I try to run run.sh I see the following:

Starting Tether...
../linux/adb: error while loading shared libraries: libncurses.so.5: wrong ELF class: ELFCLASS64

module.js:340
    throw err;
          ^
Error: Cannot find module 'chainsaw'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/powit/git/github/Tether/node-tuntap/node_modules/binary/index.js:1:78)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

**Comment by bemehiser** [comment]
Yes, 64 bit is supported, or at least that's what I always used. Are you entirely sure you're using a 64 bit compiler on a 64 bit architecture? You can check gcc architecture with `gcc -v`.
